package com.gabrielrochon.loqio;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * JPA entity representing a vocabulary item in the PostgreSQL database.
 * This class maps to the "vocabulary" table and contains translations
 * between Tagalog and English words.
 */
@Entity
@Table(name = "vocabulary")
public class Item
{

	// Unique identifier for the vocabulary item. Auto-generated by the db.
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	// The Tagalog word or phrase.
	private String tagalog;

	// The English translation.
	private String english;

	// Constructors
	public Item() {}

	public Item(String tagalog, String english)
	{
		this.tagalog = tagalog;
		this.english = english;
	}

	// Getters and Setters
	public Long getId()
	{
		return id;
	}

	public void setId(Long id)
	{
		this.id = id;
	}

	public String getTagalog()
	{
		return tagalog;
	}

	public void setTagalog(String tagalog)
	{
		this.tagalog = tagalog;
	}

	public String getEnglish()
	{
		return english;
	}

	public void setEnglish(String english)
	{
		this.english = english;
	}

	@Override
	public String toString()
	{
		return "Item{" +
				"id=" + id +
				", tagalog='" + tagalog + '\'' +
				", english='" + english + '\'' +
				'}';
	}
}
