package com.gabrielrochon.languagecontent.sentence;

import com.gabrielrochon.languagecontent.module.Module;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * JPA entity representing a sentence in the PostgreSQL database.
 * This class maps to the "sentence" table and has a many-to-one relationship with Module.
 */
@Entity
@Table(name = "sentence")
public class Sentence
{

	// Unique identifier for the sentence. Auto-generated by the db.
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	// The module this sentence belongs to.
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "module_id")
	private Module module;

	// The position of the sentence.
	private Integer position;

	// The learning text of the sentence.
	private String learningText;

	// The translation text of the sentence.
	private String translationText;

	// The speaker identifier.
	private Integer speaker;

	// Constructors
	public Sentence() {}

	public Sentence(Module module, Integer position, String learningText, String translationText, Integer speaker)
	{
		this.module = module;
		this.position = position;
		this.learningText = learningText;
		this.translationText = translationText;
		this.speaker = speaker;
	}

	// Getters and Setters
	public Long getId()
	{
		return id;
	}

	public void setId(Long id)
	{
		this.id = id;
	}

	public Module getModule()
	{
		return module;
	}

	public void setModule(Module module)
	{
		this.module = module;
	}

	public Integer getPosition()
	{
		return position;
	}

	public void setPosition(Integer position)
	{
		this.position = position;
	}

	public String getLearningText()
	{
		return learningText;
	}

	public void setLearningText(String learningText)
	{
		this.learningText = learningText;
	}

	public String getTranslationText()
	{
		return translationText;
	}

	public void setTranslationText(String translationText)
	{
		this.translationText = translationText;
	}

	public Integer getSpeaker()
	{
		return speaker;
	}

	public void setSpeaker(Integer speaker)
	{
		this.speaker = speaker;
	}

	@Override
	public String toString()
	{
		return "Sentence{" +
				"id=" + id +
				", module=" + (module != null ? module.getId() : null) +
				", position=" + position +
				", learningText='" + learningText + '\'' +
				", translationText='" + translationText + '\'' +
				", speaker=" + speaker +
				'}';
	}
}
