package com.gabrielrochon.languagecontent.language;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * JPA entity representing a language in the PostgreSQL database.
 * This class maps to the "language" table.
 */
@Entity
@Table(name = "language")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Language
{

	// Unique identifier for the language. Auto-generated by the db.
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	// The name of the language.
	private String name;

	// URL for the background image stored in Azure Blob Storage.
	private String backgroundImageUrl;

	// ISO 3166-1 alpha-2 country code (e.g., "CA", "US", "FR")
	private String countryCode;

	// Presentation description of the language
	private String languagePresentation;

	// Constructors
	public Language() {}

	public Language(String name)
	{
		this.name = name;
	}

	public Language(String name, String backgroundImageUrl)
	{
		this.name = name;
		this.backgroundImageUrl = backgroundImageUrl;
	}

	// Getters and Setters
	public String getLanguagePresentation()
	{
		return languagePresentation;
	}

	public void setLanguagePresentation(String languagePresentation)
	{
		this.languagePresentation = languagePresentation;
	}

	// Other Getters and Setters
	public Long getId()
	{
		return id;
	}

	public void setId(Long id)
	{
		this.id = id;
	}

	public String getName()
	{
		return name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getBackgroundImageUrl()
	{
		return backgroundImageUrl;
	}

	public void setBackgroundImageUrl(String backgroundImageUrl)
	{
		this.backgroundImageUrl = backgroundImageUrl;
	}

	public String getCountryCode()
	{
		return countryCode;
	}

	public void setCountryCode(String countryCode)
	{
		this.countryCode = countryCode;
	}

	@Override
	public String toString()
	{
		return "Language{" +
				"id=" + id +
				", name='" + name + '\'' +
				", backgroundImageUrl='" + backgroundImageUrl + '\'' +
				", countryCode='" + countryCode + '\'' +
				", languagePresentation='" + languagePresentation + '\'' +
				'}';
	}
}
