package com.gabrielrochon.languagecontent.language;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * JPA entity representing a language in the PostgreSQL database.
 * This class maps to the "language" table.
 */
@Entity
@Table(name = "language")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Language
{

	// Unique identifier for the language. Auto-generated by the db.
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	// The name of the language.
	private String name;

	// Constructors
	public Language() {}

	public Language(String name)
	{
		this.name = name;
	}

	// Getters and Setters
	public Long getId()
	{
		return id;
	}

	public void setId(Long id)
	{
		this.id = id;
	}

	public String getName()
	{
		return name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@Override
	public String toString()
	{
		return "Language{" +
				"id=" + id +
				", name='" + name + '\'' +
				'}';
	}
}
