package com.gabrielrochon.languagecontent.module;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.gabrielrochon.languagecontent.language.Language;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * JPA entity representing a module in the PostgreSQL database.
 * This class maps to the "module" table and has a many-to-one relationship with Language.
 */
@Entity
@Table(name = "module")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Module
{

	// Unique identifier for the module. Auto-generated by the db.
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	// The language this module belongs to.
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "language_id")
	private Language language;

	// The name of the module.
	private String name;

	// Description of the module.
	private String description;

	// Presentation content for the module.
	private String modulePresentation;

	// Material icon name for the module.
	private String materialIconName;

	// Constructors
	public Module() {}

	public Module(Language language, String name)
	{
		this.language = language;
		this.name = name;
	}

	public Module(Language language, String name, String description)
	{
		this.language = language;
		this.name = name;
		this.description = description;
	}

	public Module(Language language, String name, String description, String modulePresentation)
	{
		this.language = language;
		this.name = name;
		this.description = description;
		this.modulePresentation = modulePresentation;
	}

	public Module(Language language, String name, String description, String modulePresentation, String materialIconName)
	{
		this.language = language;
		this.name = name;
		this.description = description;
		this.modulePresentation = modulePresentation;
		this.materialIconName = materialIconName;
	}

	// Getters and Setters
	public Long getId()
	{
		return id;
	}

	public void setId(Long id)
	{
		this.id = id;
	}

	public Language getLanguage()
	{
		return language;
	}

	public void setLanguage(Language language)
	{
		this.language = language;
	}

	public String getName()
	{
		return name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getDescription()
	{
		return description;
	}

	public void setDescription(String description)
	{
		this.description = description;
	}

	public String getModulePresentation()
	{
		return modulePresentation;
	}

	public void setModulePresentation(String modulePresentation)
	{
		this.modulePresentation = modulePresentation;
	}

	public String getMaterialIconName()
	{
		return materialIconName;
	}

	public void setMaterialIconName(String materialIconName)
	{
		this.materialIconName = materialIconName;
	}

	@Override
	public String toString()
	{
		return "Module{" +
				"id=" + id +
				", language=" + (language != null ? language.getId() : null) +
				", name='" + name + '\'' +
				", description='" + description + '\'' +
				", modulePresentation='" + modulePresentation + '\'' +
				", materialIconName='" + materialIconName + '\'' +
				'}';
	}
}
